# Copyright 2026 The Magma GPU Project
# SPDX-License-Identifier: MIT

from __future__ import annotations
import tomllib
from pathlib import Path
import typing as T

from gorgonzola.common import (
    OutputType,
    ApiInfo,
    CopyrightInfo,
    ApiData,
    GorgonzolaConstant,
    GorgonzolaEnumEntry,
    GorgonzolaEnum,
    GorgonzolaFlag,
    GorgonzolaApiObject,
    GorgonzolaConstantArray,
    GorgonzolaStruct,
    GorgonzolaExtensibleStruct,
    GorgonzolaCommand,
    RUST_TYPE_INFO_MAP,
    BaseRustTypeInfo,
    ApiAspectMask,
    API_ASPECT_MAP,
    CommonGenerator,
    GorgonzolaStructMember,
    GorgonzolaTypeInstance,
    Direction,
    FfiConfig,
    EncoderConfig,
    DecoderConfig,
)
from gorgonzola.post_process import PostProcessedApiData

from gorgonzola.ffi_generator import FFIGenerator
from gorgonzola.header_generator import HeaderGenerator
from gorgonzola.protocol_generator import (
    ProtocolGenerator,
    RustApiGenerator,
)
from gorgonzola.encode_generator import EncodeGenerator
from gorgonzola.decode_generator import DecodeGenerator


class ApiSection(T.TypedDict, total=False):
    name: str
    major_version: int
    minor_version: int
    patch_version: int


class CopyrightSection(T.TypedDict, total=False):
    spdx: str
    holder: str
    year: int


class ClientOutDir(T.TypedDict, total=False):
    ffi: str
    header: str
    protocol: str
    autogenerated_rust_api: str
    protocol_impl: str
    rust_api: str
    encoder: str
    decoder: str


class ServerOutDir(T.TypedDict, total=False):
    protocol: str
    autogenerated_rust_api: str
    protocol_impl: str
    rust_api: str
    encoder: str
    decoder: str


class OutDirInfoSection(T.TypedDict, total=False):
    client: ClientOutDir
    server: ServerOutDir


class ApiToml(T.TypedDict, total=False):
    api: ApiSection
    copyright: CopyrightSection
    out_dir_info: OutDirInfoSection
    ffi: FfiConfig
    encoder: EncoderConfig
    decoder: DecoderConfig


class ApiObjectDict(T.TypedDict, total=False):
    name: str
    aspects: T.List[str]


class DefinitionsToml(T.TypedDict, total=False):
    api_objects: T.List[T.Union[str, ApiObjectDict]]
    constants: T.List[Constant]
    enums: T.List[Enum]
    flags: T.List[Enum]


class StructsToml(T.TypedDict, total=False):
    structs: T.List[Struct]
    extensible_structs: T.List[ExtensibleStruct]


class Constant(T.TypedDict, total=False):
    name: str
    type: str
    value: int
    aspects: T.List[str]


class EnumEntry(T.TypedDict, total=False):
    name: str
    value: int


class Enum(T.TypedDict, total=False):
    name: str
    type: str
    entries: T.Union[T.Dict[str, int], T.List[EnumEntry]]
    aspects: T.List[str]


class Array(T.TypedDict, total=False):
    dynamic: bool
    size: str
    array_size: str


class StructMember(T.TypedDict, total=False):
    name: str
    type: str
    array: Array


class Stype(T.TypedDict, total=False):
    name: str
    value: int


class Struct(T.TypedDict, total=False):
    name: str
    members: T.List[StructMember]
    aspects: T.List[str]


class ExtensibleStruct(T.TypedDict, total=False):
    name: str
    members: T.List[StructMember]
    stype: Stype
    stype_value: int
    extends: str
    rust_member_name: str
    aspects: T.List[str]


class CommandInput(T.TypedDict, total=False):
    name: str
    type: str
    array: Array
    direction: str


class Command(T.TypedDict, total=False):
    name: str
    command_name: str
    target: str
    rust_target: str
    inputs: T.List[CommandInput]
    output: str
    aspects: T.List[str]
    destructor: bool
    is_destructor: bool
    response: bool
    manual: bool


class CommandsToml(T.TypedDict, total=False):
    commands: T.List[Command]


_T = T.TypeVar('_T')


def load_toml(file: Path, type_hint: T.Type[_T]) -> _T:
    with file.open(mode='rb') as f:
        return T.cast(_T, tomllib.load(f))


class ApiGenerator:
    def __init__(self, directory: Path, out_dir: Path, output_type: OutputType) -> None:
        self.directory = directory
        self.out_dir = out_dir
        self.output_type = output_type
        self.generators: T.List[CommonGenerator] = []
        self.common_api_data = ApiData()
        self.api_info: ApiInfo | None = None
        self.copyright_info: CopyrightInfo | None = None

    def _parse_aspect_mask(
        self, item: T.Mapping[str, object], default: ApiAspectMask = ApiAspectMask.COMMON
    ) -> ApiAspectMask:
        aspects = item.get('aspects')
        if not isinstance(aspects, list):
            return default
        mask = ApiAspectMask.NONE
        for aspect in aspects:
            mask |= API_ASPECT_MAP[str(aspect)]
        return mask

    def _add_type(
        self, item: GorgonzolaTypeInstance, aspect: ApiAspectMask = ApiAspectMask.NONE
    ) -> None:
        item.aspect_mask = aspect
        self.common_api_data.add_type(item)

    def _add_command(
        self, item: GorgonzolaCommand, aspect: ApiAspectMask = ApiAspectMask.COMMON
    ) -> None:
        item.aspect_mask = aspect
        self.common_api_data.add_command(item)

    def parse(self) -> T.Optional[ApiGenerator]:
        output_data = self._parse_api_toml()
        if output_data is None:
            return None

        if not self._parse_definitions_toml():
            return None

        if not self._parse_structs_toml():
            return None

        if not self._parse_commands_toml():
            return None

        post_processed_api_data = PostProcessedApiData(self.common_api_data)
        self._configure_generators(output_data, post_processed_api_data)
        return self

    def emit(self) -> None:
        for generator in self.generators:
            generator.emit()

    def _parse_api_toml(self) -> T.Optional[OutDirInfoSection]:
        api_toml_path = self.directory / 'api.toml'
        api_toml = load_toml(api_toml_path, ApiToml)

        api_data = api_toml['api']
        copyright_data = api_toml['copyright']

        self.api_info = ApiInfo(
            name=api_data['name'],
            major_version=api_data['major_version'],
            minor_version=api_data['minor_version'],
            patch_version=api_data['patch_version'],
        )

        self.copyright_info = CopyrightInfo(
            spdx=copyright_data['spdx'],
            holder=copyright_data['holder'],
            year=copyright_data['year'],
        )
        self.common_api_data.api_name = self.api_info.name
        self.common_api_data.ffi_config = api_toml.get('ffi', {})
        self.common_api_data.encoder_config = api_toml.get('encoder', {})
        self.common_api_data.decoder_config = api_toml.get('decoder', {})

        return api_toml.get('out_dir_info', {})

    def _configure_generators(
        self, output_data: OutDirInfoSection, post_processed_api_data: PostProcessedApiData
    ) -> None:
        copyright_info = self.copyright_info
        api_name = self.api_info.name

        def add_gen(cls: T.Type[CommonGenerator], rel_path: T.Optional[str]) -> None:
            if rel_path:
                self.generators.append(
                    cls(self.out_dir / Path(rel_path), copyright_info, api_name, post_processed_api_data)
                )

        if self.output_type == OutputType.CLIENT:
            client = output_data.get('client', {})
            add_gen(FFIGenerator, client.get('ffi'))
            add_gen(HeaderGenerator, client.get('header'))
            add_gen(ProtocolGenerator, client.get('protocol'))
            add_gen(
                RustApiGenerator,
                client.get('autogenerated_rust_api')
                or client.get('rust_api')
                or client.get('protocol_impl'),
            )
            add_gen(EncodeGenerator, client.get('encoder'))
            add_gen(DecodeGenerator, client.get('decoder'))
        elif self.output_type == OutputType.SERVER:
            server = output_data.get('server', {})
            add_gen(ProtocolGenerator, server.get('protocol'))
            add_gen(
                RustApiGenerator,
                server.get('autogenerated_rust_api')
                or server.get('rust_api')
                or server.get('protocol_impl'),
            )
            add_gen(DecodeGenerator, server.get('decoder') or server.get('encoder'))

    def _parse_enum_entries(
        self, entries_data: T.Union[T.Dict[str, int], T.List[EnumEntry]]
    ) -> T.List[GorgonzolaEnumEntry]:
        if isinstance(entries_data, dict):
            return [GorgonzolaEnumEntry(name=k, value=v) for k, v in entries_data.items()]
        return [GorgonzolaEnumEntry(name=e['name'], value=e['value']) for e in entries_data]

    def _parse_base_enum(
        self,
        cls: T.Type[GorgonzolaEnum] | T.Type[GorgonzolaFlag],
        item: Enum,
        kind: str,
    ) -> None:
        name = item['name']
        entries = self._parse_enum_entries(item['entries'])
        type_info = RUST_TYPE_INFO_MAP.get(item['type'])
        if not type_info:
            raise ValueError(f'Unknown underlying type {item["type"]} for {kind} {name}')
        mask = self._parse_aspect_mask(item)
        self._add_type(cls(name, type_info, entries), mask)

    def _parse_definitions_toml(self) -> bool:
        definitions_toml = load_toml(self.directory / 'definitions.toml', DefinitionsToml)

        if 'api_objects' in definitions_toml:
            for item in definitions_toml['api_objects']:
                match item:
                    case str():
                        self._add_type(GorgonzolaApiObject(item), ApiAspectMask.COMMON)
                    case dict():
                        mask = self._parse_aspect_mask(item)
                        self._add_type(GorgonzolaApiObject(item['name']), mask)

        if 'constants' in definitions_toml:
            for c in definitions_toml['constants']:
                mask = self._parse_aspect_mask(c)
                self._add_type(GorgonzolaConstant(c['name'], c['type'], c['value']), mask)

        if 'enums' in definitions_toml:
            for e in definitions_toml['enums']:
                self._parse_base_enum(GorgonzolaEnum, e, 'enum')

        if 'flags' in definitions_toml:
            for f in definitions_toml['flags']:
                self._parse_base_enum(GorgonzolaFlag, f, 'flag')

        return True

    def _register_struct_declaration(self, struct_data: Struct) -> None:
        name = struct_data['name']
        aspect_mask = self._parse_aspect_mask(struct_data, default=ApiAspectMask.NONE)
        struct_obj = GorgonzolaStruct(name=name, members=[])
        self._add_type(struct_obj, aspect_mask)

    def _register_extensible_struct_declaration(self, struct_data: ExtensibleStruct) -> None:
        name = struct_data['name']
        aspect_mask = self._parse_aspect_mask(struct_data, default=ApiAspectMask.NONE)
        stype_data = struct_data['stype']
        stype = stype_data.get('name', '')
        stype_value = stype_data.get('value', 0)
        extends = struct_data.get('extends')
        rust_member_name = struct_data.get('rust_member_name')
        struct_obj = GorgonzolaExtensibleStruct(
            name=name,
            members=[],
            stype=stype,
            stype_value=stype_value,
            extends=extends,
            rust_member_name=rust_member_name,
        )
        self._add_type(struct_obj, aspect_mask)

    def _resolve_member_type(
        self, member: T.Union[StructMember, CommandInput]
    ) -> GorgonzolaTypeInstance:
        type_name = member['type']
        if 'array' in member:
            array = member['array']
            size = array.get('size') or array.get('array_size')
            if size:
                arr_name = f'[{type_name}; {size}]'
                if arr_name not in self.common_api_data.arrays:
                    resolved_elem_type = self.common_api_data.resolve_type_name(type_name)
                    array_type = GorgonzolaConstantArray(arr_name, resolved_elem_type, str(size))
                    self._add_type(array_type)
                type_name = arr_name
        return self.common_api_data.resolve_type_name(type_name)

    def _resolve_struct_members(
        self,
        struct_data: T.Union[Struct, ExtensibleStruct],
        struct_dict: T.Mapping[str, GorgonzolaStruct],
    ) -> None:
        name = struct_data['name']
        struct_obj = struct_dict[name]
        for member in struct_data.get('members', []):
            resolved_type = self._resolve_member_type(member)
            is_pointer = member.get('pointer', False)
            struct_obj.members.append(
                GorgonzolaStructMember(
                    name=member['name'],
                    type=resolved_type,
                    is_pointer=is_pointer,
                )
            )

    def _parse_structs_toml(self) -> bool:
        data = load_toml(self.directory / 'structs.toml', StructsToml)

        structs_list = data.get('structs', [])
        ext_structs_list = data.get('extensible_structs', [])

        for s in structs_list:
            self._register_struct_declaration(s)

        for s in ext_structs_list:
            self._register_extensible_struct_declaration(s)

        for s in structs_list:
            self._resolve_struct_members(s, self.common_api_data.structs)

        for s in ext_structs_list:
            self._resolve_struct_members(s, self.common_api_data.extensible_structs)

        # Validate extensible structs
        stype_values: T.Set[int] = set()
        for s in ext_structs_list:
            name = s['name']
            struct_obj = self.common_api_data.extensible_structs[name]
            if struct_obj.stype_value in stype_values:
                raise ValueError(
                    f"Duplicate stype_value '{struct_obj.stype_value}' in extensible struct '{name}'."
                )
            stype_values.add(struct_obj.stype_value)

            if struct_obj.extends:
                if struct_obj.extends not in self.common_api_data.extensible_structs:
                    raise ValueError(
                        f"Extensible struct '{name}' specifies extends='{struct_obj.extends}', "
                        f'which is not a defined extensible struct.'
                    )

        return True

    def _parse_commands_toml(self) -> bool:
        data = load_toml(self.directory / 'commands.toml', CommandsToml)
        if 'commands' in data:
            for opcode_val, command in enumerate(data['commands'], start=1):
                name = command['name']
                aspect_mask = self._parse_aspect_mask(command, default=ApiAspectMask.COMMON)
                manual = command.get('manual', False)

                inputs = self._parse_fields(command.get('inputs', []))

                ret_name = command.get('output') or 'void'
                ret = self.common_api_data.resolve_type_name(ret_name)
                target = command.get('target', command.get('rust_target'))
                is_destructor = command.get('destructor', command.get('is_destructor', False))
                response = command.get('response', False)

                self._add_command(
                    GorgonzolaCommand(
                        name=name,
                        ret=ret,
                        inputs=inputs,
                        opcode=opcode_val,
                        target=target,
                        is_destructor=is_destructor,
                        response=response,
                        manual=manual,
                    ),
                    aspect_mask,
                )
        return True

    def _parse_fields(self, fields_data: T.List[CommandInput]) -> T.List[GorgonzolaStructMember]:
        fields = []
        for f in fields_data:
            resolved_type = self._resolve_member_type(f)
            direction_str = f.get('direction')
            if direction_str not in (Direction.IN, Direction.INOUT):
                raise ValueError(
                    f'Invalid direction "{direction_str}" for input "{f.get("name")}". '
                    'Must be "in" or "inout".'
                )
            direction = Direction(direction_str)
            fields.append(
                GorgonzolaStructMember(name=f['name'], type=resolved_type, direction=direction)
            )
        return fields
